### ISSUE TITLE
Doesn't work server-side, registry 

### ISSUE THREAD

**Issue by sternschnaube** [chinaqianb/Wind_Bottle#1]

**Comment by chinaqianb** [comment]
> _未提供说明。_

After testing, the mod works on the server. Please check if this mod is also installed on the server

**Comment by venaminecraft** [comment]
What I mean is, it doesn't works server-side only. It's forced on the client as well.

**Comment by chinaqianb** [comment]
> What I mean is, it doesn't works server-side only. It's forced on the client as well.

oh，I check  codes ，it sure hava a bug in version 1.0.0,the  version 1.0.1 is fixed.
thank you for the issue
[https://github.com/chinaqianb/Wind_Bottle/releases/download/1.0.1/wind_bottle-fabric-1.21-1.0.1.jar](url)

**Comment by venaminecraft** [comment]
Thank you very much. It worked ☺️

**Comment by venaminecraft** [comment]
I tested now v1.0.3 and the registry error still happens 😕

**Comment by chinaqianb** [comment]
> 我现在测试了 v1.0.3，注册表错误仍然发生 😕

I test it,but is no error,please send a video or more specific description🤔

**Comment by venaminecraft** [comment]
When I try to connect to the server, mod installed just on server-side, it shows my client a registry mismatch error. The same as before 😕
Is there no way for this mod to work just server-side?

**Comment by chinaqianb** [comment]
> 当我尝试连接到服务器时，mod 仅安装在服务器端，它向我的客户端显示注册表不匹配错误。和以前😕一样：这个模组没有办法只在服务器端工作吗？
you try installed the mod in both client and server, then try again

**Comment by venaminecraft** [comment]
If that's the need then I'm wrong here.
Thought it can be used just as server-side one.
Thanks 😄
